{"topicSections":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionAPI","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionEntity","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Telemetry","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Troubleshooting","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Your-First-AVP-CloudXR-Client"],"anchor":"Articles"},{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRSession","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HmdProperties","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/MockSession","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Session","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/TrackingSystem"],"anchor":"Classes"},{"generated":true,"anchor":"Protocols","title":"Protocols","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionQualityListener"]},{"generated":true,"anchor":"Structures","title":"Structures","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRSessionComponent","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Config","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/DebugVizConfig","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/FetchHmdPropertiesImmersiveSpace","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HUDConfig","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HUDView"]},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/clientStatsVersion"]},{"identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/registerSystems()"],"title":"Functions","anchor":"Functions","generated":true},{"title":"Enumerations","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/AuthenticationType","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/ConnectionType","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/DebugVizMode","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/DejitterProfile","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/FeedbackReason","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HandTrackingMode","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/ResolutionPreset","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionError","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionState","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/StreamingError","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/TelemetryConsentType"],"anchor":"Enumerations","generated":true},{"generated":true,"title":"Extended Modules","anchor":"Extended-Modules","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/RealityFoundation","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Swift","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/simd"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"CloudXRKit","role":"collection","modules":[{"name":"CloudXRKit"}],"roleHeading":"Framework","symbolKind":"module","title":"CloudXRKit"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit"},"abstract":[{"text":"Stream immersive applications.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/cloudxrkit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/cloudxrkit"]}],"kind":"symbol","primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"inlineContent":[{"text":"CloudXRKit provides streaming capabilities to native visionOS applications.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[[]]},"references":{"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/Swift":{"role":"collection","abstract":[],"title":"Swift","url":"\/documentation\/cloudxrkit\/swift","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Swift"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit":{"role":"collection","url":"\/documentation\/cloudxrkit","title":"CloudXRKit","type":"topic","abstract":[{"type":"text","text":"Stream immersive applications."}],"kind":"symbol","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/AuthenticationType":{"kind":"symbol","navigatorTitle":[{"text":"AuthenticationType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationType"}],"url":"\/documentation\/cloudxrkit\/authenticationtype","role":"symbol","abstract":[{"type":"text","text":"NVIDIA Graphics Delivery Network (GDN) authentication type."}],"type":"topic","title":"AuthenticationType","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/AuthenticationType"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/SessionQualityListener":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SessionQualityListener","kind":"identifier"}],"title":"SessionQualityListener","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionQualityListener","navigatorTitle":[{"kind":"identifier","text":"SessionQualityListener"}],"url":"\/documentation\/cloudxrkit\/sessionqualitylistener"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/DebugVizConfig":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DebugVizConfig"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DebugVizConfig"}],"url":"\/documentation\/cloudxrkit\/debugvizconfig","role":"symbol","abstract":[],"type":"topic","title":"DebugVizConfig","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/DebugVizConfig"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/CloudXRKitVersionNumber":{"role":"symbol","fragments":[{"text":"CloudXRKitVersionNumber","kind":"identifier"}],"title":"CloudXRKitVersionNumber","kind":"symbol","abstract":[{"type":"text","text":"Project version number for CloudXRKit."}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRKitVersionNumber","url":"\/documentation\/cloudxrkit\/cloudxrkitversionnumber"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/TelemetryConsentType":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/TelemetryConsentType","navigatorTitle":[{"text":"TelemetryConsentType","kind":"identifier"}],"title":"TelemetryConsentType","url":"\/documentation\/cloudxrkit\/telemetryconsenttype","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TelemetryConsentType"}]},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/CloudXRKitVersionString":{"kind":"symbol","fragments":[{"text":"CloudXRKitVersionString","kind":"identifier"}],"url":"\/documentation\/cloudxrkit\/cloudxrkitversionstring","role":"symbol","abstract":[{"type":"text","text":"Project version string for CloudXRKit."}],"type":"topic","title":"CloudXRKitVersionString","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRKitVersionString"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/FetchHmdPropertiesImmersiveSpace":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FetchHmdPropertiesImmersiveSpace","kind":"identifier"}],"type":"topic","abstract":[{"text":"Prebuilt ","type":"text"},{"type":"codeVoice","code":"Scene"},{"text":" used by ","type":"text"},{"type":"codeVoice","code":"HmdProperties.beginIpdCheck()"},{"text":" to measure IPD and other important geometry for remote rendering.","type":"text"}],"navigatorTitle":[{"text":"FetchHmdPropertiesImmersiveSpace","kind":"identifier"}],"title":"FetchHmdPropertiesImmersiveSpace","url":"\/documentation\/cloudxrkit\/fetchhmdpropertiesimmersivespace","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/FetchHmdPropertiesImmersiveSpace","role":"symbol","kind":"symbol"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/SessionEntity":{"role":"article","title":"Session Component & Entity","kind":"article","abstract":[{"type":"text","text":"API to add and control the remote rendered scene to your immersive view."}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionEntity","url":"\/documentation\/cloudxrkit\/sessionentity"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/SessionState":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SessionState","kind":"identifier"}],"title":"SessionState","navigatorTitle":[{"kind":"identifier","text":"SessionState"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionState","kind":"symbol","url":"\/documentation\/cloudxrkit\/sessionstate"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/CloudXRSession":{"kind":"symbol","navigatorTitle":[{"text":"CloudXRSession","kind":"identifier"}],"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRSession","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CloudXRSession","kind":"identifier"}],"url":"\/documentation\/cloudxrkit\/cloudxrsession","abstract":[{"type":"text","text":"Manages a CloudXR session."}],"title":"CloudXRSession","type":"topic","role":"symbol"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/HmdProperties":{"kind":"symbol","navigatorTitle":[{"text":"HmdProperties","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HmdProperties"}],"url":"\/documentation\/cloudxrkit\/hmdproperties","role":"symbol","abstract":[{"type":"text","text":"Stores important HMD geometry characteristics required for accurate remote rendering."}],"type":"topic","title":"HmdProperties","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HmdProperties"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/Config":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Config","kind":"identifier"}],"title":"Config","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Config","kind":"identifier"}],"abstract":[{"text":"Specifies how to configure a Session.","type":"text"}],"url":"\/documentation\/cloudxrkit\/config","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Config"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/SessionAPI":{"role":"article","title":"Session API","kind":"article","abstract":[{"type":"text","text":"API to manage the life cycle of a session with the server."}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionAPI","url":"\/documentation\/cloudxrkit\/sessionapi"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/Your-First-AVP-CloudXR-Client":{"kind":"article","url":"\/documentation\/cloudxrkit\/your-first-avp-cloudxr-client","role":"article","abstract":[],"type":"topic","title":"Your First CloudXR Client for AVP","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Your-First-AVP-CloudXR-Client"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/TrackingSystem":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TrackingSystem","kind":"identifier"}],"title":"TrackingSystem","kind":"symbol","abstract":[{"type":"text","text":"Sends device tracking state to CloudXR."}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/TrackingSystem","navigatorTitle":[{"text":"TrackingSystem","kind":"identifier"}],"url":"\/documentation\/cloudxrkit\/trackingsystem"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/RealityFoundation":{"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/RealityFoundation","abstract":[],"kind":"symbol","url":"\/documentation\/cloudxrkit\/realityfoundation","role":"collection","type":"topic","title":"RealityFoundation"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/clientStatsVersion":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientStatsVersion","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"url":"\/documentation\/cloudxrkit\/clientstatsversion","role":"symbol","abstract":[],"type":"topic","title":"clientStatsVersion","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/clientStatsVersion"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/registerSystems()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerSystems","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/registerSystems()","abstract":[{"text":"Registers Systems for rendering CloudXR sessions into RealityKit Scenes.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/cloudxrkit\/registersystems()","kind":"symbol","title":"registerSystems()"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/MockSession":{"abstract":[{"text":"Manages a Mock session.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/cloudxrkit\/mocksession","title":"MockSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockSession"}],"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/MockSession","navigatorTitle":[{"text":"MockSession","kind":"identifier"}],"type":"topic"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/Session":{"abstract":[{"type":"text","text":"Base class for a session see "},{"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRSession","isActive":true,"type":"reference"}],"kind":"symbol","role":"symbol","url":"\/documentation\/cloudxrkit\/session","title":"Session","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Session","kind":"identifier"}],"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Session","navigatorTitle":[{"kind":"identifier","text":"Session"}],"type":"topic"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/simd":{"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/simd","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/cloudxrkit\/simd","title":"simd","kind":"symbol"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/ResolutionPreset":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResolutionPreset","kind":"identifier"}],"type":"topic","abstract":[{"text":"Choice between various rendering\/streaming resolution combinations for achieving the desired visual quality.","type":"text"}],"navigatorTitle":[{"text":"ResolutionPreset","kind":"identifier"}],"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/ResolutionPreset","title":"ResolutionPreset","url":"\/documentation\/cloudxrkit\/resolutionpreset","kind":"symbol"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/Troubleshooting":{"role":"article","title":"Troubleshooting","kind":"article","abstract":[{"type":"text","text":"Troubleshooting client issues"}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Troubleshooting","url":"\/documentation\/cloudxrkit\/troubleshooting"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/HandTrackingMode":{"kind":"symbol","navigatorTitle":[{"text":"HandTrackingMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HandTrackingMode"}],"url":"\/documentation\/cloudxrkit\/handtrackingmode","role":"symbol","abstract":[{"type":"text","text":"Settings for hand tracking."}],"type":"topic","title":"HandTrackingMode","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HandTrackingMode"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/StreamingError":{"title":"StreamingError","abstract":[{"text":"Classification of stream errors.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/StreamingError","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StreamingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StreamingError"}],"url":"\/documentation\/cloudxrkit\/streamingerror"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/DejitterProfile":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DejitterProfile"}],"title":"DejitterProfile","kind":"symbol","abstract":[{"type":"text","text":"Changes the amount of client-side buffering for absorbing networking jitter before frames are displayed."}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/DejitterProfile","navigatorTitle":[{"text":"DejitterProfile","kind":"identifier"}],"url":"\/documentation\/cloudxrkit\/dejitterprofile"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/FeedbackReason":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FeedbackReason","kind":"identifier"}],"title":"FeedbackReason","kind":"symbol","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/FeedbackReason","url":"\/documentation\/cloudxrkit\/feedbackreason","role":"symbol","abstract":[{"type":"text","text":"Predefined types of issues that users can specify in their feedback."}],"navigatorTitle":[{"kind":"identifier","text":"FeedbackReason"}],"type":"topic"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/CloudXRSessionComponent":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloudXRSessionComponent","kind":"identifier"}],"identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRSessionComponent","navigatorTitle":[{"kind":"identifier","text":"CloudXRSessionComponent"}],"abstract":[{"text":"Represents a CloudXR session that can be rendered into a RealityKit Scene.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/cloudxrkit\/cloudxrsessioncomponent","kind":"symbol","title":"CloudXRSessionComponent"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/HUDConfig":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDConfig"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"HUDConfig","kind":"identifier"}],"url":"\/documentation\/cloudxrkit\/hudconfig","role":"symbol","abstract":[{"text":"Specifies how to configure heads-up-disaply (HUD) visualization.","type":"text"}],"type":"topic","title":"HUDConfig","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HUDConfig"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/DebugVizMode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DebugVizMode"}],"title":"DebugVizMode","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/DebugVizMode","navigatorTitle":[{"kind":"identifier","text":"DebugVizMode"}],"url":"\/documentation\/cloudxrkit\/debugvizmode"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/HUDView":{"abstract":[{"text":"Head-Up Display (HUD) view for visualizing performance metrics.","type":"text"}],"url":"\/documentation\/cloudxrkit\/hudview","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/HUDView","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"HUDView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUDView"}],"title":"HUDView"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/ConnectionType":{"kind":"symbol","navigatorTitle":[{"text":"ConnectionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConnectionType","kind":"identifier"}],"url":"\/documentation\/cloudxrkit\/connectiontype","role":"symbol","abstract":[],"type":"topic","title":"ConnectionType","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/ConnectionType"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/Telemetry":{"role":"article","title":"Telemetry","kind":"article","abstract":[{"text":"Anonymous collection of system performance data to enhance service quality.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Telemetry","url":"\/documentation\/cloudxrkit\/telemetry"},"doc://com.nvidia.CloudXRKit/documentation/CloudXRKit/SessionError":{"abstract":[{"text":"Error types for invalid session operations.","type":"text"}],"url":"\/documentation\/cloudxrkit\/sessionerror","identifier":"doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionError","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SessionError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SessionError"}],"title":"SessionError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"anchor":"Articles","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionAPI","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/SessionEntity","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Telemetry","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Troubleshooting","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/Your-First-AVP-CloudXR-Client"],"title":"Articles"},{"title":"Variables","identifiers":["doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRKitVersionNumber","doc:\/\/com.nvidia.CloudXRKit\/documentation\/CloudXRKit\/CloudXRKitVersionString"],"anchor":"Variables","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}